version: '3.8'

services:
  cookies-app:
    container_name: cookies-app
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"   # Map cổng 5000 máy ngoài vào 8080 trong container
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__CookiesAuthenDb=Server=192.168.1.225,1433;Database=MyLearningDB;User Id=sa;Password=123456aA@;TrustServerCertificate=True;MultipleActiveResultSets=true
      - ConnectionStrings__RedisConnection=redis:6379
      - MessageBroker__Host=rabbitmq
    depends_on:     
      - redis
      - rabbitmq
    #restart: unless-stopped
  redis:
    image: redis:alpine
    container_name: redis-cache
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - default # Để chung network thì App mới gọi được
  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    ports:
      - "5540:5540"
    #restart: unless-stopped
    volumes:
      - redis_insight_data:/data
    networks:
      - default # Để chung mạng với service redis
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"   # Cổng để Code .NET kết nối
      - "15672:15672" # Cổng để vào Web quản lý (Giao diện)
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - default 
volumes:
  redis_insight_data:
  rabbitmq_data: